#! /usr/bin/python
# coding: UTF-8
#
# Author: David García (miemailito@gmail.com) Github: Copperfield
# Version: 0.35

# Este script instalará en cualquier sistema los elementos 
# y aplicaciones para construir la personalización
#
# TODO: Esto funcionará para Windows, Mac y Linux pero de momento
# sólo para linux.
#
# TODO: Mirar una herramienta de colores (colorama...)
#
# TODO: Peparar funcióm para sacar del código los mensajes de error
# TODO: Añadir contol de excepciones


# Detectar sistema operativo OK
# Instalar Vim (Faltan archivos por agregar a las carpetas)
# Instalar OhMyZsh OK
# Si procede cambiar el xorg.conf para dos monitores OK

import os
from shutil import copy2, copytree

yes=["s","si","SI","Sí","SÍ","yes","Yes","YEs","YES","y"]

def detectOs():
    """
    Función que devuelve el sistema operativo usado
    """

    print "Detectando tú sistema operativo....\033[1;32m OK \033[0m"
    return os.name

def configAndInstall(name, pathDst = os.getenv("HOME"), dst='/', install=True):
    """
    Método genérico para instalar las aplicaciones
    """
   
    # Listar los directorios
    ret = ""
    names = os.listdir(str(name))
    response = raw_input("¿Deseas instalar y configurar \033[1;33m" + name + "\033[0m (SI | no): ")
    if response in yes:
        if "install" in names:
            os.chdir(name)
            os.system("./install")
            os.chdir("..")
        else:
            # Instalar el paquete
            if install:
                os.system("sudo apt-get install " + name)
                # Copiar los directorios y fcheros necesarios
                for files in names:
                   ret =+ os.system("cp -r "+ name + "/" + files + " "+ pathDst+"/")
        # Añado los códigos de colores
        status = ("\033[1;33m FAIL \033[0m" if ret else "\033[1;32m OK \033[0m") 
        print "Configurando \033[1;33m "+ name + "\033[0m  finalizada.... " + status


# Hilo de ejecución principal   
if __name__ == "__main__":
    nameOs = detectOs()
    if nameOs == "posix": 
        configAndInstall("vim")
        configAndInstall("ohMyZsh")
