#! /usr/bin/python
# coding: UTF-8
#
# Author: David García (miemailito@gmail.com) Github: Copperfield
#
# Este script instalará en cualquier sistema los elementos 
# y aplicaciones para construir la personalización
#
# TODO: Esto funcionará para Windows, Mac y Linux pero de momento
# sólo para linux.
#
# TODO: Mirar una herramienta de colores (colorama...)

# Detectar sistema operativo
# Instalar Vim
# Instalar OhMyZsh
# Si procede cambiar el xorg.conf para dos monitores

import os
from shutil import copy2, copytree

yes=["s","si","SI","Sí","SÍ","yes","Yes","YEs","YES","y"]

def detectOs():
    """
    Función que devuelve el sistema operativo usado
    """

    print "Detectando tú sistema operativo....\033[1;32m OK \033[0m"
    return os.name

def configAndInstall(name, pathDst=os.getenv("HOME"), dst='/', install=True):
    """
    Configura e aplicacion
    """
    # Listar los directorios
    names = os.listdir(str(name))
    response = raw_input("¿Deseas instalar y configurar \033[1;33m" + name + "\033[0m (SI | no): ")
    if response in yes:
        # Instalar el paquete
        if install:
            os.system("sudo apt-get install " + name)
        # Copiar los directorios y fcheros necesarios
        for files in names:
            ret =+ os.system("cp -r "+ name + "/" + files + " "+ pathDst+"/")
        if ret:
            status= "\033[1;31m FAIL \033[0m"
        else:
            status= "\033[1;32m OK \033[0m"
        print "Configurando \033[1;33m "+ name+ "\033[0m .... " + status

# Hilo de ejecución principal   
if __name__ == "__main__":
    nameOs = detectOs()
    if nameOs == "posix":
        #TODO: Añadir el directorio /.vim para los plugin 
        configAndInstall("vim")
